# Generated by Django 4.2.6 on 2023-10-05 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('info', models.CharField(max_length=225)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.category')),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL)),
                ('executor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_increase_mode', models.BooleanField(blank=True, default=True)),
                ('is_protected_mode', models.BooleanField(blank=True, default=False)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('percentage_reduction', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('step_price', models.IntegerField()),
                ('interval', models.IntegerField(default=8)),
                ('is_winner_exist', models.BooleanField(blank=True, default=False)),
                ('is_step_taken', models.BooleanField(blank=True, default=False)),
                ('is_run', models.BooleanField(blank=True, default=False)),
                ('is_done', models.BooleanField(blank=True, default=False)),
                ('is_stop', models.BooleanField(blank=True, default=False)),
                ('unregister_executor_name', models.CharField(max_length=25)),
                ('unregister_executor_contacts', models.CharField(max_length=225)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_auction', to=settings.AUTH_USER_MODEL)),
                ('executor_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_auction', to=settings.AUTH_USER_MODEL)),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
            options={
                'verbose_name': 'Аукцион',
                'verbose_name_plural': 'Аукционы',
            },
        ),
    ]
