# Generated by Django 4.2.6 on 2023-10-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='unregister_executor_contacts',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='unregister_executor_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
